version: '3.5'
services:
  node:
    container_name: nuxt
    #build: .  # local image build
    image: geospatialweb/nuxt:latest  # docker cloud repository image
    command: node server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./usr/src/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
  postgres:
    container_name: postgis
    image: mdillon/postgis:11-alpine
    restart: always
    volumes:
      - ./data/pg.sql:/docker-entrypoint-initdb.d/pg.sql
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
